# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4hn62Aa6yWS2DMrFSPjGkHzaljaE6N9
"""

import streamlit as st

# Your information
name = "Your Name"
favorite_food = "Your Favorite Food"
degree = "Your College Degree"

# Title of the app with your information
st.title("Welcome to My Streamlit App!")
st.write(f"**Name**: {name}")
st.write(f"**Favorite Food**: {favorite_food}")
st.write(f"**Degree**: {degree}")