# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4hn62Aa6yWS2DMrFSPjGkHzaljaE6N9
"""

import streamlit as st

# Your information
name = "Jerry Lu, Sebastian Abetya, Carlos Barreto, Mya Yannoni, Jazon Kubiak"
favorite_activity = "Games, Videos, Reading, Playing Basketball"
favorite_color = "Blue, Green, Red, Purple"

# Title of the app with your information
st.title("Peace Engineering Class Assignment #5")
st.write(f"**Names**: {name}")
st.write(f"**Favorite Activity**: {favorite_activity}")
st.write(f"**Favorite Color**: {favorite_color}")
